"""Vercel Python serverless function that renders a proposal PDF.

Vercel's Node runtime cannot run ReportLab, so this half of the app is Python.
It lives beside the Next.js routes and is reached at /api/render; the JS route
at /api/generate does the content binding and then calls this.

Deliberately built on the stdlib handler rather than FastAPI: the server is
provided by the platform, so a web framework would add megabytes to the bundle
and buy nothing.

The renderer modules and a copy of the spec sit in _renderer/, generated by
`npm run sync-spec` and committed - a serverless bundle can only see files
inside its own directory tree.
"""

from __future__ import annotations

import base64
import json
import re
import sys
import tempfile
from http.server import BaseHTTPRequestHandler
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "_renderer"))

from palette import Palette  # noqa: E402
from replay import Replayer  # noqa: E402

MAX_BODY_BYTES = 12_000_000
MAX_LOGO_BYTES = 5_000_000
DATA_URL = re.compile(r"^data:image/(png|jpeg|jpg|gif);base64,(.+)$", re.IGNORECASE)


def _write_logos(logos: dict | None, tmp: Path) -> dict[str, str]:
    """Turns data URLs into files on disk, which is what the renderer expects."""
    paths: dict[str, str] = {}
    for frame, data_url in (logos or {}).items():
        match = DATA_URL.match(data_url or "")
        if not match:
            continue
        raw = base64.b64decode(match.group(2))
        if len(raw) > MAX_LOGO_BYTES:
            continue
        ext = "jpeg" if match.group(1).lower() in ("jpg", "jpeg") else match.group(1).lower()
        path = tmp / f"{frame}.{ext}"
        path.write_bytes(raw)
        paths[frame] = str(path)
    return paths


class handler(BaseHTTPRequestHandler):  # noqa: N801 - Vercel requires this name
    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 - stdlib naming
        self._send_json(200, {"status": "ok", "spec": str(Replayer.__module__)})

    def do_POST(self) -> None:  # noqa: N802 - stdlib naming
        try:
            length = int(self.headers.get("Content-Length") or 0)
            if length <= 0 or length > MAX_BODY_BYTES:
                self._send_json(400, {"error": f"unsupported body size: {length}"})
                return

            req = json.loads(self.rfile.read(length))

            try:
                palette = Palette.load(req.get("theme"))
            except ValueError as exc:
                self._send_json(400, {"error": str(exc)})
                return

            with tempfile.TemporaryDirectory(prefix="proposal-") as tmpdir:
                tmp = Path(tmpdir)
                out = tmp / "proposal.pdf"

                replayer = Replayer(
                    req.get("template", "seo-only"),
                    palette=palette,
                    content=req.get("content"),
                    replacements=list((req.get("replacements") or {}).items()),
                    logos=_write_logos(req.get("logos"), tmp),
                    keep_empty_logo_panels=bool(req.get("keep_empty_logo_panels")),
                    icon_style=req.get("icon_style", "none"),
                )
                report = replayer.render(out)
                pdf = out.read_bytes()

            self.send_response(200)
            self.send_header("Content-Type", "application/pdf")
            self.send_header("Content-Length", str(len(pdf)))
            # Diagnostics ride along in headers so the browser can surface them
            # without a second request; the body stays a plain PDF.
            self.send_header("X-Overflow-Count", str(len(report.overflows)))
            self.send_header("X-Overflow-Detail", " | ".join(report.overflows[:5]))
            self.send_header("X-Logos-Drawn", str(report.logos_drawn))
            self.send_header("X-Substitutions", str(report.substitutions))
            self.end_headers()
            self.wfile.write(pdf)

        except FileNotFoundError as exc:
            self._send_json(400, {"error": str(exc)})
        except Exception as exc:  # noqa: BLE001 - surface the reason, never a blank 500
            self._send_json(500, {"error": f"{type(exc).__name__}: {exc}"})
